import React from "react";
import { Col, Table } from "react-bootstrap";
import "./../../css/candidates.css";
import { FiEdit } from "react-icons/fi";
import { GoLink } from "react-icons/go";
import { RiDeleteBinLine } from "react-icons/ri";

const CandidatesTable = () => {
  const candidates = [
    {
      fullName: "ABC",
      jobTitle: "React Developer",
      exp: 4,
      tools: " Vs code, PostMan",
      skills: "ReactJs, Redux, Javascript, Html, Css",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "XYZ",
      jobTitle: "Full Stack Developer",
      exp: 4,
      tools: " Vs code, PostMan",
      skills: "ReactJs, Redux, Javascript, Html, Css, NodeJs",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "XYZ",
      jobTitle: "UI/UX Developer",
      exp: 4,
      tools: " vs code",
      skills: " Html, Css",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "ABC",
      jobTitle: "React Developer",
      exp: 4,
      tools: " vs code, PostMan",
      skills: "ReactJs, Redux, Javascript, Html, Css",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "XYZ",
      jobTitle: "Full Stack Developer",
      exp: 4,
      tools: " Vs code, PostMan",
      skills: "ReactJs, Redux, Javascript, Html, Css, NodeJs",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "XYZ",
      jobTitle: "UI/UX Developer",
      exp: 4,
      tools: " vs code",
      skills: " Html, Css",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "ABC",
      jobTitle: "React Developer",
      exp: 4,
      tools: " vs code, PostMan",
      skills: "ReactJs, Redux, Javascript, Html, Css",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "XYZ",
      jobTitle: "Full Stack Developer",
      exp: 4,
      tools: " Vs code, PostMan",
      skills: "ReactJs, Redux, Javascript, Html, Css, NodeJs",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "XYZ",
      jobTitle: "UI/UX Developer",
      exp: 4,
      tools: " vs code",
      skills: " Html, Css",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "ABC",
      jobTitle: "React Developer",
      exp: 4,
      tools: " vs code, PostMan",
      skills: "ReactJs, Redux, Javascript, Html, Css",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "XYZ",
      jobTitle: "Full Stack Developer",
      exp: 4,
      tools: " Vs code, PostMan",
      skills: "ReactJs, Redux, Javascript, Html, Css, NodeJs",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "XYZ",
      jobTitle: "UI/UX Developer",
      exp: 4,
      tools: " vs code",
      skills: " Html, Css",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "ABC",
      jobTitle: "React Developer",
      exp: 4,
      tools: " vs code, PostMan",
      skills: "ReactJs, Redux, Javascript, Html, Css",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "XYZ",
      jobTitle: "Full Stack Developer",
      exp: 4,
      tools: " Vs code, PostMan",
      skills: "ReactJs, Redux, Javascript, Html, Css, NodeJs",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "XYZ",
      jobTitle: "UI/UX Developer",
      exp: 4,
      tools: " vs code",
      skills: " Html, Css",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "ABC",
      jobTitle: "React Developer",
      exp: 4,
      tools: " vs code, PostMan",
      skills: "ReactJs, Redux, Javascript, Html, Css",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "XYZ",
      jobTitle: "Full Stack Developer",
      exp: 4,
      tools: " Vs code, PostMan",
      skills: "ReactJs, Redux, Javascript, Html, Css, NodeJs",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "XYZ",
      jobTitle: "UI/UX Developer",
      exp: 4,
      tools: " vs code",
      skills: " Html, Css",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "ABC",
      jobTitle: "React Developer",
      exp: 4,
      tools: " vs code, PostMan",
      skills: "ReactJs, Redux, Javascript, Html, Css",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "XYZ",
      jobTitle: "Full Stack Developer",
      exp: 4,
      tools: " Vs code, PostMan",
      skills: "ReactJs, Redux, Javascript, Html, Css, NodeJs",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "XYZ",
      jobTitle: "UI/UX Developer",
      exp: 4,
      tools: " vs code",
      skills: " Html, Css",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "ABC",
      jobTitle: "React Developer",
      exp: 4,
      tools: " vs code, PostMan",
      skills: "ReactJs, Redux, Javascript, Html, Css",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "XYZ",
      jobTitle: "Full Stack Developer",
      exp: 4,
      tools: " Vs code, PostMan",
      skills: "ReactJs, Redux, Javascript, Html, Css, NodeJs",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "XYZ",
      jobTitle: "UI/UX Developer",
      exp: 4,
      tools: " vs code",
      skills: " Html, Css",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "ABC",
      jobTitle: "React Developer",
      exp: 4,
      tools: " vs code, PostMan",
      skills: "ReactJs, Redux, Javascript, Html, Css",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "XYZ",
      jobTitle: "Full Stack Developer",
      exp: 4,
      tools: " Vs code, PostMan",
      skills: "ReactJs, Redux, Javascript, Html, Css, NodeJs",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "XYZ",
      jobTitle: "UI/UX Developer",
      exp: 4,
      tools: " vs code",
      skills: " Html, Css",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "ABC",
      jobTitle: "React Developer",
      exp: 4,
      tools: " vs code, PostMan",
      skills: "ReactJs, Redux, Javascript, Html, Css",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "XYZ",
      jobTitle: "Full Stack Developer",
      exp: 4,
      tools: " Vs code, PostMan",
      skills: "ReactJs, Redux, Javascript, Html, Css, NodeJs",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "XYZ",
      jobTitle: "UI/UX Developer",
      exp: 4,
      tools: " vs code",
      skills: " Html, Css",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "ABC",
      jobTitle: "React Developer",
      exp: 4,
      tools: " vs code, PostMan",
      skills: "ReactJs, Redux, Javascript, Html, Css",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "XYZ",
      jobTitle: "Full Stack Developer",
      exp: 4,
      tools: " Vs code, PostMan",
      skills: "ReactJs, Redux, Javascript, Html, Css, NodeJs",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "XYZ",
      jobTitle: "UI/UX Developer",
      exp: 4,
      tools: " vs code",
      skills: " Html, Css",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "ABC",
      jobTitle: "React Developer",
      exp: 4,
      tools: " vs code, PostMan",
      skills: "ReactJs, Redux, Javascript, Html, Css",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "XYZ",
      jobTitle: "Full Stack Developer",
      exp: 4,
      tools: " Vs code, PostMan",
      skills: "ReactJs, Redux, Javascript, Html, Css, NodeJs",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "XYZ",
      jobTitle: "UI/UX Developer",
      exp: 4,
      tools: " vs code",
      skills: " Html, Css",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "ABC",
      jobTitle: "React Developer",
      exp: 4,
      tools: " vs code, PostMan",
      skills: "ReactJs, Redux, Javascript, Html, Css",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "XYZ",
      jobTitle: "Full Stack Developer",
      exp: 4,
      tools: " Vs code, PostMan",
      skills: "ReactJs, Redux, Javascript, Html, Css, NodeJs",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "XYZ",
      jobTitle: "UI/UX Developer",
      exp: 4,
      tools: " vs code",
      skills: " Html, Css",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "ABC",
      jobTitle: "React Developer",
      exp: 4,
      tools: " vs code, PostMan",
      skills: "ReactJs, Redux, Javascript, Html, Css",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "XYZ",
      jobTitle: "Full Stack Developer",
      exp: 4,
      tools: " Vs code, PostMan",
      skills: "ReactJs, Redux, Javascript, Html, Css, NodeJs",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "XYZ",
      jobTitle: "UI/UX Developer",
      exp: 4,
      tools: " vs code",
      skills: " Html, Css",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "ABC",
      jobTitle: "React Developer",
      exp: 4,
      tools: " vs code, PostMan",
      skills: "ReactJs, Redux, Javascript, Html, Css",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "XYZ",
      jobTitle: "Full Stack Developer",
      exp: 4,
      tools: " Vs code, PostMan",
      skills: "ReactJs, Redux, Javascript, Html, Css, NodeJs",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "XYZ",
      jobTitle: "UI/UX Developer",
      exp: 4,
      tools: " vs code",
      skills: " Html, Css",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "ABC",
      jobTitle: "React Developer",
      exp: 4,
      tools: " vs code, PostMan",
      skills: "ReactJs, Redux, Javascript, Html, Css",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "XYZ",
      jobTitle: "Full Stack Developer",
      exp: 4,
      tools: " Vs code, PostMan",
      skills: "ReactJs, Redux, Javascript, Html, Css, NodeJs",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "XYZ",
      jobTitle: "UI/UX Developer",
      exp: 4,
      tools: " vs code",
      skills: " Html, Css",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "ABC",
      jobTitle: "React Developer",
      exp: 4,
      tools: " vs code, PostMan",
      skills: "ReactJs, Redux, Javascript, Html, Css",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "XYZ",
      jobTitle: "Full Stack Developer",
      exp: 4,
      tools: " Vs code, PostMan",
      skills: "ReactJs, Redux, Javascript, Html, Css, NodeJs",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
    {
      fullName: "XYZ",
      jobTitle: "UI/UX Developer",
      exp: 4,
      tools: " vs code",
      skills: " Html, Css",
      practice: "Microsoft",
      billingDate: 1 + "$",
      target: "25/09/2021",
      earlyStartingDate: "15/09/2021",
    },
  ];
  const headCell = {
    backgroundColor: "#cae1fe",
  };
  return (
    <Col>
      <Table striped bordered hover>
        <thead>
          <tr>
            <td style={headCell}>Id</td>
            <td style={headCell}>Full Name</td>
            <td style={headCell}>Job Title</td>
            <td style={headCell}>Exp</td>
            <td style={headCell}>Tool</td>
            <td style={headCell}>Skills</td>

            <td style={headCell}>Practice</td>
            <td style={headCell}>Billing Rate</td>
            <td style={headCell}>Target Date</td>
            <td style={headCell}>Early starting date</td>
            <td style={headCell}>{"         "}</td>
          </tr>
        </thead>

        <tbody>
          {candidates.map((candidate, i) => {
            return (
              <tr key={i + 1}>
                <td>{i + 1}</td>
                <td>{candidate.fullName}</td>
                <td>{candidate.jobTitle}</td>
                <td>{candidate.exp}</td>
                <td>{candidate.tools}</td>
                <td>{candidate.skills}</td>
                <td>{candidate.practice}</td>
                <td>{candidate.billingDate}</td>
                <td>{candidate.target}</td>
                <td>{candidate.earlyStartingDate}</td>
                <td className="eud">
                  <FiEdit />
                  <GoLink name="user" />
                  <RiDeleteBinLine />
                </td>
              </tr>
            );
          })}
        </tbody>
        <tfoot>
          <tr>
            <td colSpan="8"></td>
          </tr>
        </tfoot>
      </Table>
    </Col>
  );
};

export default CandidatesTable;
